services:
  aischedulerbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - ./service-account.json:/app/service-account.json
    command: python bot.py